config/routes.rb
Gotospace::Application.routes.draw do
  devise_for :users
  root :to => 'lists#index'
  resources :lists do
    resources :todos do
      post 'toggle'
    end
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list
  belongs_to :todo
  has_many :todos

  after_initialize :set_default

  def set_default
    self.completed = false if self.completed == nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_many :todos, :through => :lists
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def show
    @list = current_user.lists.find(params[:id])
    @todos = @list.todos.where(completed: false)
  end

  def new
    @list = current_user.lists.new
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def create
    @list = current_user.lists.new(params[:list])

    if @list.save
       redirect_to @list, notice: 'List was successfully created.'
    else
       render 'new'
    end
  end

  def update
    @list = current_user.lists.find(params[:id])

    if @list.update_attributes(params[:list])
     redirect_to @list, notice: 'List was successfully updated.'
    else
     render 'edit'
    end
  end

  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy

    redirect_to [:lists]
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :find_list
  # GET /todos
  # GET /todos.json
  def index
    @todos = @list.todos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = @list.todos.find(params[:todo_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = @list.todos.build
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = @list.todos.new(params[:todo])

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @list, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :ok }
    end
  end

  def toggle
    @todo = Todo.find(params[:todo_id])
    @todo.completed = !@todo.completed
    @todo.save
    redirect_to @list
  end

  private
    def find_list
      @list = current_user.lists.find(params[:list_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gotospace</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="header">
    <h1>GO TO SPACE</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <div id="content">
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) if user_signed_in? %>

      <%= yield %>
    </div>
    <div id="footer">
      All content copyright &copy; 2011 gotospace inc.
    </div>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
    <%= f.label :name %>: 
    <%= f.text_field :name %>
  </div>
  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', [:lists] %>

app/views/lists/index.html.erb
<h3>Your Lists:</h3>

<ul>
<% @lists.each do |list| %>
  <li><%= link_to list.name, list %></li>
<% end %>
</ul>
<br />

<%= link_to 'New List', [:new, :list] %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', [:lists] %>

app/views/lists/show.html.erb
<h3><%= @list.name %></h3>
<h4>Todos:</h4>
<%= render @todos %>
<p><%= link_to 'New Todo', new_list_todo_path(@list) %></p>

<%= link_to 'Edit ' + @list.name, edit_list_path(@list) %> |
<%= link_to 'Delete', @list, confirm: 'Are you sure?', method: :delete %>
<%= link_to 'Back', lists_path %>

app/views/todos/_form.html.erb
<%= form_for([@list, @todo]) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li><%= link_to 'X', [@list, todo, :toggle], method: :post %> :: <%= todo.name %></li>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.name %></td>
    <td><%= todo.completed %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_list_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_list_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', list_todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo.name %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo.completed %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>